export type Preset = { label: string; paths: string[] };

export const PRESETS: Preset[] = [
  {
    label: "mixed",
    paths: [
      "unknown_file",
      "unknown_folder/",
      "src/",
      "src/index.ts",
      "src/App.tsx",
      "public/",
      "public/favicon.ico",
      "node_modules/",
      ".github/",
      ".github/workflows/ci.yml",
      "dist/",
      "package.json",
      "tsconfig.json",
      "pnpm-lock.yaml",
      ".gitignore",
      ".env",
      "Dockerfile",
      "README.md",
      "LICENSE",
    ],
  },
  {
    label: "files",
    paths: [
      "unknown_file",
      "index.ts",
      "index.js",
      "App.tsx",
      "App.vue",
      "main.py",
      "main.go",
      "main.rs",
      "Main.java",
      "app.rb",
      "index.html",
      "styles.css",
      "styles.scss",
      "package.json",
      "tsconfig.json",
      "Cargo.toml",
      "go.mod",
      "pyproject.toml",
      "Dockerfile",
      "Makefile",
      "compose.yaml",
      "vite.config.ts",
      ".gitignore",
      ".env",
      "README.md",
      "LICENSE",
    ],
  },
  {
    label: "folders",
    paths: [
      "unknown_folder/",
      "src/",
      "public/",
      "dist/",
      "build/",
      "app/",
      "pages/",
      "components/",
      "hooks/",
      "lib/",
      "utils/",
      "api/",
      "test/",
      "docs/",
      "scripts/",
      "config/",
      "assets/",
      "images/",
      "node_modules/",
      "vendor/",
      ".github/",
      ".vscode/",
      ".git/",
      ".husky/",
    ],
  },
];

export const DEFAULT_PATHS = PRESETS[0].paths.join("\n");
